server:
  port: 8082

spring:
  application:
    name: notification-service

  data:
    redis:
      host: localhost
      port: 6379

springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    path: /notification-service/swagger-ui.html

management:
  endpoints:
    web:
      exposure:
        include: health, metrics, prometheus
  endpoint:
    health:
      show-details: always
  metrics:
    tags:
      application: ${spring.application.name}

  newrelic:
    metrics:
      export:
        enabled: true
        api-key: ${NEW_RELIC_API_KEY}
        account-id: ${NEW_RELIC_ACCOUNT_ID}
        uri: https://metric-api.eu.newrelic.com/metric/v1