server:
  port: 8082

spring:
  application:
    name: notification-service

  data:
    redis:
      host: localhost
      port: 6379

springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    path: notification-service/swagger-ui.html