server:
  port: 8082
  servlet:
    context-path: /notification-service

spring:
  application:
    name: notification-service

springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    path: /swagger-ui.html

management:
  endpoints:
    web:
      exposure:
        include: health, metrics, prometheus
  endpoint:
    health:
      show-details: always
  newrelic:
    metrics:
      export:
        enabled: true
        accountId: 6619351
        apiKey: eu01xx7a671e99c058932413fd4964e3FFFFNRAL
        uri: https://metric-api.eu.newrelic.com
        step: 30s