server:
  port: 8084

spring:
  application:
    name: transaction-service

  data:
    redis:
      host: localhost
      port: 6379

springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    path: transaction-service/swagger-ui.html


management:
  endpoints:
    web:
      exposure:
        include: "health,info,metrics,prometheus"

  metrics:
    tags:
      application: ${spring.application.name}

  endpoint:
    prometheus:
      enabled: true

logging:
  level:
    root: INFO
    com.revolink: DEBUG
    org.springframework.web: DEBUG