server:
  port: 8082

spring:
  application:
    name: transaction-service

  data:
    redis:
      host: localhost
      port: 6379

management:
  endpoints:
    web:
      exposure:
        include: "health,info,metrics,prometheus"

  metrics:
    tags:
      application: ${spring.application.name}

  endpoint:
    prometheus:
      enabled: true

logging:
  level:
    org.springframework.boot.actuate.endpoint.web: DEBUG