server:
  port: 8084

spring:
  application:
    name: transaction-service

  data:
    redis:
      host: localhost
      port: 6379

springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    path: /transaction-service/swagger-ui.html

management:
  endpoints:
    web:
      exposure:
        include: health, info, metrics, prometheus
  endpoint:
    prometheus:
      enabled: true
  metrics:
    tags:
      application: ${spring.application.name}

  newrelic:
    metrics:
      export:
        enabled: true
        api-key: ${NEW_RELIC_API_KEY}
        account-id: ${NEW_RELIC_ACCOUNT_ID}
        uri: https://metric-api.eu.newrelic.com/metric/v1

logging:
  level:
    root: INFO
    com.revolink: DEBUG
    org.springframework.web: DEBUG