server:
  port: 8084
  servlet:
    context-path: /transaction-service

spring:
  application:
    name: transaction-service

springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    path: /swagger-ui.html

management:
  endpoints:
    web:
      exposure:
        include: health, info, metrics, prometheus
  endpoint:
    prometheus:
      enabled: true
  newrelic:
    metrics:
      export:
        enabled: true
        account-id: 6619351
        api-key: eu01xx7a671e99c058932413fd4964e3FFFFNRAL
        uri: https://metric-api.eu.newrelic.com
        step: 30s

logging:
  level:
    root: INFO
    com.revolink: DEBUG
    org.springframework.web: DEBUG
