server:
  port: 8083
  servlet:
    context-path: /exchange-service

spring:
  application:
    name: exchange-service

springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    path: /swagger-ui.html

logging:
  level:
    com.revolink.exchange: WARN