server:
  port: 8083

spring:
  application:
    name: exchange-service

springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    path: /exchange-service/swagger-ui.html

logging:
  level:
    com.revolink.exchange: DEBUG