global:
  scrape_interval: 5s

scrape_configs:
  - job_name: 'wallet-service'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['wallet-service:8080']

  - job_name: 'transaction-service'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['transaction-service:8084']

  - job_name: 'notification-service'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['notification-service:8082']

  - job_name: 'exchange-service'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['exchange-service:8083']